# Generated by Django 3.2.4 on 2021-07-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='удалена'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='href',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='адрес(ссылка)'),
        ),
    ]
